/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    team: Team;
    offers: Offer;
    media: Media;
    enquiries: Enquiry;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-status': SiteStatus;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-status': SiteStatusSelect<false> | SiteStatusSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page of the site. Edit the wording and photos here, then press Publish website on the dashboard.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Name in this list only. Not shown on the site.
   */
  title: string;
  /**
   * The page address. Fixed.
   */
  path: string;
  slug: string;
  template:
    | 'home'
    | 'about'
    | 'team'
    | 'offers'
    | 'contact'
    | 'book'
    | 'hub'
    | 'category'
    | 'service'
    | 'emergency'
    | 'legal'
    | 'sitemap'
    | 'blog';
  hero?: {
    h1: string;
    intro?: string | null;
    hero_image?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
  };
  home?: {
    h1: string;
    hero_intro?: string | null;
    hero_image?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    trust_line?: string | null;
    stat_label?: string | null;
    stat_number?: string | null;
    stat_text?: string | null;
    chips_title?: string | null;
    chips?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    funds_caption?: string | null;
    welcome_eyebrow?: string | null;
    welcome_lead?: string | null;
    welcome_statement?: string | null;
    float_image_1?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    float_image_2?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    services_heading?: string | null;
    services_intro?: string | null;
    /**
     * Six cards. The links and icons are fixed; the wording is yours.
     */
    service_cards?:
      | {
          title?: string | null;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
    why_heading?: string | null;
    why_text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    features?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    story_heading?: string | null;
    story_text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    story_image?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    offers_heading?: string | null;
    visit_heading?: string | null;
    visit_intro?: string | null;
  };
  about?: {
    story_heading?: string | null;
    story?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    philosophy_heading?: string | null;
    philosophy_text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    philosophy_image?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    tech_heading?: string | null;
    tech_intro?: string | null;
    tech_cards?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    tech_outro?: string | null;
    continuity_heading?: string | null;
    continuity_text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    continuity_image?: {
      /**
       * Leave empty to keep the built-in photo.
       */
      upload?: (number | null) | Media;
      /**
       * The file the site launched with. Shown when no upload is chosen.
       */
      path?: string | null;
      alt?: string | null;
    };
    visit_heading?: string | null;
    visit_text?: string | null;
  };
  offers_page?: {
    intro_heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    footnote?: string | null;
  };
  contact?: {
    find_text?: string | null;
    message_heading?: string | null;
    message_text?: string | null;
    emergency_heading?: string | null;
    emergency_text?: string | null;
  };
  emergency?: {
    banner?: string | null;
    wait_heading?: string | null;
    wait_cards?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    wait_note?: string | null;
    seen_heading?: string | null;
    seen_body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  hub?: {
    category_cards?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    extra_cards?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  category?: {
    cards_heading?: string | null;
    cards?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The copy sections down the page, in page order. Layout stays as designed; the wording and photos are yours.
   */
  sections?:
    | {
        key?: string | null;
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        hasImage?: boolean | null;
        image?: {
          /**
           * Leave empty to keep the built-in photo.
           */
          upload?: (number | null) | Media;
          /**
           * The file the site launched with. Shown when no upload is chosen.
           */
          path?: string | null;
          alt?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What Google shows as the blue link. 50 to 60 characters is ideal. Include the practice name.
   */
  metaTitle?: string | null;
  /**
   * The grey text under the link in Google. 120 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Shown when the page is shared on Facebook, LinkedIn or by message. 1200 x 630 works best.
   */
  ogImage?: {
    /**
     * Leave empty to keep the built-in photo.
     */
    upload?: (number | null) | Media;
    /**
     * The file the site launched with. Shown when no upload is chosen.
     */
    path?: string | null;
    alt?: string | null;
  };
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos and images for the site. Every image needs alt text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo in a short sentence. Screen readers and Google read this.
   */
  alt: string;
  builtinPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Articles on the blog. Save as draft while writing; publish when ready, then press Publish website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The H1 at the top of the article.
   */
  title: string;
  /**
   * Lowercase words joined by hyphens. Changing this on a published post breaks links to it; add a redirect if you must.
   */
  slug: string;
  category: string;
  datePublished: string;
  /**
   * Leave empty to use the publish date.
   */
  dateModified?: string | null;
  /**
   * One or two sentences shown on the blog index card.
   */
  excerpt: string;
  /**
   * Shown at the top of the article and on the blog index. Landscape, at least 1200px wide.
   */
  featuredImage?: {
    /**
     * Leave empty to keep the built-in photo.
     */
    upload?: (number | null) | Media;
    /**
     * The file the site launched with. Shown when no upload is chosen.
     */
    path?: string | null;
    alt?: string | null;
  };
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Required by AHPRA guidance for articles about surgical or invasive procedures.
   */
  surgicalDisclaimer?: boolean | null;
  /**
   * Up to three. Shown under the article.
   */
  related?: (number | Post)[] | null;
  /**
   * What Google shows as the blue link. 50 to 60 characters is ideal. Include the practice name.
   */
  metaTitle?: string | null;
  /**
   * The grey text under the link in Google. 120 to 160 characters.
   */
  metaDescription?: string | null;
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The practitioners on the Meet the Team page, in order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Lower numbers first.
   */
  order: number;
  /**
   * Portrait orientation works best.
   */
  photo?: {
    /**
     * Leave empty to keep the built-in photo.
     */
    upload?: (number | null) | Media;
    /**
     * The file the site launched with. Shown when no upload is chosen.
     */
    path?: string | null;
    alt?: string | null;
  };
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For GYA records. Not shown on the site.
   */
  ahpraNumber?: string | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Offer cards on the Special Offers page and the homepage. Every offer must state its price, what it includes and when it ends.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * e.g. $135
   */
  price?: string | null;
  order: number;
  note?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta_label?: string | null;
  /**
   * Optional. Hidden from the site before this date.
   */
  startDate?: string | null;
  /**
   * Optional. Drops off the site after this date (on the next publish).
   */
  endDate?: string | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every form submission from the website, whether or not the email got through.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  formType?: ('appointment' | 'contact' | 'newsletter') | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  service?: string | null;
  preferred?: string | null;
  message?: string | null;
  emailStatus?: ('sent' | 'failed') | null;
  emailError?: string | null;
  followedUp?: boolean | null;
  /**
   * Page the form was sent from.
   */
  page?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old address to a new one. Takes effect on the next publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path on this site, e.g. /old-page/
   */
  from: string;
  /**
   * Path or full URL to send visitors to.
   */
  to: string;
  type?: ('301' | '302') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  slug?: T;
  template?: T;
  hero?:
    | T
    | {
        h1?: T;
        intro?: T;
        hero_image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
      };
  home?:
    | T
    | {
        h1?: T;
        hero_intro?: T;
        hero_image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        trust_line?: T;
        stat_label?: T;
        stat_number?: T;
        stat_text?: T;
        chips_title?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        funds_caption?: T;
        welcome_eyebrow?: T;
        welcome_lead?: T;
        welcome_statement?: T;
        float_image_1?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        float_image_2?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        services_heading?: T;
        services_intro?: T;
        service_cards?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
        why_heading?: T;
        why_text?: T;
        features?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        story_heading?: T;
        story_text?: T;
        story_image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        offers_heading?: T;
        visit_heading?: T;
        visit_intro?: T;
      };
  about?:
    | T
    | {
        story_heading?: T;
        story?: T;
        philosophy_heading?: T;
        philosophy_text?: T;
        philosophy_image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        tech_heading?: T;
        tech_intro?: T;
        tech_cards?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        tech_outro?: T;
        continuity_heading?: T;
        continuity_text?: T;
        continuity_image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        visit_heading?: T;
        visit_text?: T;
      };
  offers_page?:
    | T
    | {
        intro_heading?: T;
        intro?: T;
        footnote?: T;
      };
  contact?:
    | T
    | {
        find_text?: T;
        message_heading?: T;
        message_text?: T;
        emergency_heading?: T;
        emergency_text?: T;
      };
  emergency?:
    | T
    | {
        banner?: T;
        wait_heading?: T;
        wait_cards?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        wait_note?: T;
        seen_heading?: T;
        seen_body?: T;
      };
  hub?:
    | T
    | {
        category_cards?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        extra_cards?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  category?:
    | T
    | {
        cards_heading?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        key?: T;
        heading?: T;
        body?: T;
        hasImage?: T;
        image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  datePublished?: T;
  dateModified?: T;
  excerpt?: T;
  featuredImage?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  body?: T;
  surgicalDisclaimer?: T;
  related?: T;
  metaTitle?: T;
  metaDescription?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  photo?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  bio?: T;
  ahpraNumber?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  order?: T;
  note?: T;
  body?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta_label?: T;
  startDate?: T;
  endDate?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  builtinPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  preferred?: T;
  message?: T;
  emailStatus?: T;
  emailError?: T;
  followedUp?: T;
  page?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Practice details used across every page: phone, email, address, hours, socials, announcement bar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  practice?: {
    /**
     * Updates every Call button and the structured data.
     */
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * Used by the Get Directions buttons.
     */
    maps_url?: string | null;
    /**
     * Leave empty to hide the reviews badge on the homepage.
     */
    review_url?: string | null;
    review_label?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  /**
   * Shown on the homepage, contact page, emergency page and footer, and used for the structured data Google reads.
   */
  hours?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Closed public holidays
   */
  hours_note?: string | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status".
 */
export interface SiteStatus {
  id: number;
  lastChangedAt?: string | null;
  lastPublishedAt?: string | null;
  lastImportedAt?: string | null;
  lastPublishNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  practice?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        maps_url?: T;
        review_url?: T;
        review_label?: T;
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  hours_note?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status_select".
 */
export interface SiteStatusSelect<T extends boolean = true> {
  lastChangedAt?: T;
  lastPublishedAt?: T;
  lastImportedAt?: T;
  lastPublishNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}